- README.md
**Why:**
* When copying and pasting and only modifying the `ParameterKey` &
`ParameterValue` taskcat fails input validation
> Invalid JSON in README

- installer/docker-install-master
Current code tries a chmod on /usr/local/bin even for non-root users which fails with `chmod: cannot access '/usr/local/bin/taskcat': No such file or directory`
> Fix chmod on local path for non-root installs

- taskcat/stacker.py
See: https://github.com/aws-quickstart/taskcat/issues/36
Similar to (36), the only debugging statements are:
```
foo.append(terms)
```
//////
Again, examples are sanitized, but proof the PR works. 
```python
>>> for s3obj in contents:
...     for metadata in s3obj.items():                                                                                                                                          
...             if metadata[0] == 'Key':
...                     # Finding exact match
...                     terms = metadata[1].split("/")
...                     _found_prefix = terms[0]                                                                                                                                
...                     if (key == terms[-1]) and (_found_prefix == …
```
> Fixing S3 Prefix fuzzy validation

- taskcat/stacker.py
Needed if you want to create IAM with custom named resources. Resolves the CF error ``` Requires capabilities : [CAPABILITY_NAMED_IAM]```
> adds support to run cf templates with CAPABILITY_NAMED_IAM

- README.md
- taskcat/stacker.py
> Adding ability to fill ci/override.json with parameter overrides.

- taskcat/stacker.py
See #60 
Pudb debugging: 
```
>>> pprint(fsmap)                                                                                                                                                           
['./quickstart-linux-bastion/ci/taskcat_project_override.json',
(...)
'./quickstart-linux-bastion/NOTICE.txt',
'./quickstart-linux-bastion/LICENSE.txt']
>>> for fn in fsmap:
...   if '.old' in fn:
...    print fn
... 
>>> 
```
Original debugging from issue; over here for ease of use. 
pudb debugging: 
```
>>> pprint(fsmap)
(...)
'./quickstart-linux-bastion/README.md',
'./quickstart-linux-bastion/NOTICE.txt',
'./quickstart-linux-bastion/LICENSE.txt',
'./quickstart-linux-bastion.old/templates/linux-bastion.template',
'./quickstart-linux-bastion.old/templates/linux-bastion-master.template', …
```
> Fix for Fuzzy Matches in buildmap func.

- taskcat/stacker.py
Taskcat runs complete with and without the --public_s3_bucket flag against the sample-taskcat-project data.
> Rewriting S3 objects calls to use s3 APIs versus requests module

- taskcat/stacker.py
checks whether override key is in template (if it's not in the param json) and if it is adds it to the override. See #103 for additional context.
> override params not present in parameter json. Fixes #103

- taskcat.py
- taskcat/stacker.py
initial stab at adding linting support to taskcat.
By default only warns, to prevent changing any existing behaviors. set `-l error` to fail on errors and `-l strict` to fail on warnings as well.
> add linting support

- bin/taskcat
- taskcat/client_factory.py
- taskcat/common_utils.py
- taskcat/stacker.py
Fixes #136
Ran `python setup.py test`
invoked taskcat using the `--profile` argument
Also threw in a [commit](https://github.com/aws-quickstart/taskcat/commit/1d849626c8d900296f33aab6aba75ee190701530) that fixes a bug that prevented taskcat from exiting cleanly when `exit0` or `exit1` were called.
run taskcat using the `--profile` argument and AWS_DEFAULT_REGION not set as an environment variable.
> Fix region exception when AWS_DEFAULT_REGION not set

- taskcat/generate_reports.py
- taskcat/stacker.py
fix error when retain stacks is enabled
```
[ERROR  ] :Error describing stack named [tCaT-tag-openshift-62076d8e]
[DEBUG  ] :'ReportBuilder' object has no attribute 'retain_if_failed'
```
ran taskcat against a failing stack with retain enabled
> Fix retain if failed

- requirements.txt
This PR updates boto3 to 1.9.21 and botocore to 1.12.21 to be in line with the latest released awscli.
Currently when you have both the awscli and taskcat installed in the same virtualenv, their requirements conflict.
Ran the unit tests, which only produced deprecation warnings
None
None
> Updated boto/botocore to patch 21

- .travis.yml
- taskcat/stacker.py
currently all failures of cfn `create_stack` calls are being masked due to the catch-all `except:` which then attempts to launch a changeset. this scopes down the except to only catch a `ClientError` ending with `cannot be used with templates containing Transforms.`. So other errors, throttles, limits, etc should be surfaced.
manually tested against template containing a transform
Fixes #132
> refine when to try a changeset

- taskcat/stacker.py
There's a typo in stacker.py that tries to access cfn.exceptions
reran my failing stack after making the change and got the correct error.
Run a stack that has an invalid parameter constraint, get either 'CloudFormation' object has no attribute 'ecxeptions' or the full error.
> fixing exception/ecxeption typo

- bin/taskcat
Currently taskcat must be launched from outside the project folder. This is mildly annoying because I'm commonly running git commands and what-not from inside the project folder, and then each time I want to run tcat I need to cd out, run and cd back in.
tested launching tcat from both within and outside of the project folder.
```
cd quickstart-project-name
taskcat -c ./ci/config.yaml
```
> allow launching taskcat from within the project folder

- taskcat/__init__.py
- taskcat/s3_sync.py
- taskcat/stacker.py
Currently taskcat simply pushes all local files to a bucket on each run, regardless of whether files have changed, it also leaves files in s3 that are no longer in the local project.
This changes behavior to upload only changed files, and delete files not present locally. Speeds up upload when only small changes have been made.
adds `--upload-only` switch that syncs s3 and then exits.
launched a quickstart
Uses undocumented behavior for checksums of multipart uploads, see https://github.com/aws/aws-cli/issues/2585#issue-226758933
No longer fetching template and parameters from s3, but fetching locally instead. 
enforces template path to `templates/` and parameters to `ci/`, not sure if there are any existing quick starts that don't follow this pattern.
No unit tests yet 😞
Could use a …
> sync with S3

- taskcat/stacker.py
This PR adds validation around a user-provided bucket name. If the bucket does not exist, we do not attempt an upload.
> Verifying user-provided-bucket exists. Fixes #154

- README.md
- examples/sample-taskcat-project/ci/debug-input.json
- examples/sample-taskcat-project/ci/taskcat.yml
- examples/sample-taskcat-project/ci/taskcat_project_override.json
- examples/sample-taskcat-project/templates/debug-yaml.template
- examples/sample-taskcat-project/templates/debug.template
- taskcat/stacker.py
This PR Updates wording around a mismatch between the QSS3BucketName parameter passed to templates (either via a parameter value, or default value) and what taskcat expects as a bucket name. This PR also removes this message from occuring if the $[taskcat_autobucket] placeholder is passed. 
Additionally - this PR adds checks to the sample taskcat templates to verify overrides are working as intended.
> Updates to bucket mismatch wording; adding override validations

- .gitignore
- taskcat/s3_sync.py
Minor improvement to stop retries for `AccessDenied` errors, which are permanent. Also moves the print to before the actual upload so we can see what is busy being uploaded
test against bucket where I don't have PutObject access.
create a user without `s3:PutObject` or `s3:PutObjectACL` permission. run taskcat using that user. Uploads should not be retried, taskcat should exit(1), and output look something like:
```
[S3: -> ] s3://taskcat-tag-quickstart-redhat-openshift-0167d07c/quickstart-suse-cloud-application-platform/submodules/quickstart-aws-eks/functions/source/KubeManifest/bin/aws-iam-authenticator
[ERROR  ] :S3 upload error: Failed to upload /Users/jmmccon/quickstart-suse-cloud-application-platform/submodules/quickstart-aws-eks/functions/packages/Helm/lambda.zip to …
```
> improve error handling on s3 upload failures

- taskcat/s3_sync.py
Can specify a list of key prefixes to ignore when deciding what to delete from S3. As this is not exposed in taskcat from the cli, should result in no functional changes, just adds flexibility when using s3_sync as a library.
ran taskcat with `-u` flag. verified that expected files were uploaded/deleted.
To use as a library:
```python
from taskcat.s3_sync import S3Sync
import boto3
S3Sync.exclude_remote_path_prefixes.append("remote_path_to_keep_in_s3/")
S3Sync(boto3.client('s3'), 'mybucket, 'my-prefix', './my-project-path/', 'bucket-owner-read')
```
> enable an optional list of files to NOT delete

- README.md
- bin/taskcat
- taskcat/__init__.py
- taskcat/common_utils.py
- taskcat/lambda_build.py
- taskcat/stacker.py
Currently, projects that include lambda functions must commit zipped lambda packages to `functions/packages` and maintainers must manually ensure the contents of the zips are up to date with the `functions/source` files. 
This PR adds functionality to check for the presence of a `functions/source` folder and create zips before uploading to s3. 
Tested with several Quick Start's containing lambda source code
with this in place, zips no longer need to be committed, and `functions/packages` can be safely added to `.gitignore`
added the `--lambda-build-only` flag to create zips and exit
* Pull a Quick Start containing lambda zips
* delete the packages folder
* execute taskcat, zips should get created, uploaded to s3 and taskcat run complete successfully
> automatically generate lambda packages

- bin/taskcat
- requirements.txt
- taskcat/cfn_lint.py
- taskcat/stacker.py
* major refactor
* change lint flag to lint and exit
* various bug fixes
* improve output formatting
Tested against various quick starts
run against quick start with `--lint` to lint and exit, output should look something like:
```
> taskcat -c ./ci/config.yml --lint
...
[ERROR  ] :Linter failed to load template quickstart-redhat-openshift/templates/openshift.templatenon-exist "[Errno 2] No such file or directory: 'quickstart-redhat-openshift/templates/openshift.templatenon-exist'"
[ERROR  ] :Lint detected issues for test openshift on template quickstart-redhat-openshift/templates/openshift-master.template:
[INFO   ] :    line 226 [W2001] [Check if Parameters are Used] (Parameter ContainerAccessCIDR not used.)
[INFO   ] : …
```
> lint improvements

- taskcat/cfn_lint.py
Currently cfn-python-lint exits, instead of raising an exception under some conditions. In these cases exception handling alone doesn't do the job. This PR handles the case where regions defined in tests are not supported by cfn-lint
executed against various quickstarts.
Will add a catchall for cfn-lint exiting unexpectedly in a followup pr
test against a quickstart that includes an unsupported region like `eu-west-3`. will provide an error log, but continue to test against all supported regions:
```
[taskcat] |Queing test => quickstart-fortigate-test-ap-southeast-2
[ERROR  ] :The following regions are not supported by cfn-python-lint and will not be linted {'eu-west-3'}
[ERROR  ] :Lint detected issues for test quickstart-fortigate-test on template …
```
> only test against regions supported by cfn-python-lint

- requirements.txt
- taskcat/cfn_lint.py
handles new exception type added to cfnlint in https://github.com/awslabs/cfn-python-lint/pull/463. This should ensure that failures in the linter never result in taskcat exiting prematurely and that lint errors are correctly displayed.
tested against several quickstarts
> handle new exception type added to cfn-lint

- taskcat/common_utils.py
- taskcat/stacker.py
- tests/unittest/test_common_utils.py
Improve the error feedback when we fail to parse a parameters json file. 
Fixes #201
tested against various bad and good json params
Wrote tests to fail, refactored, coded till tests passed. I think this pr is a nice simple example of how we should be using TDD to incrementally improve the codebase, reduce risk of regressions and improve test coverage.
invalid parameter files should exit 1 with meaningful errors.
> better errors for bad json parameters

- taskcat/stacker.py
Pull request to allow partial substitution in random string tokens.  For example: "$[taskcat_random-string].t.quickstart.awspartner.com" should only replace the token part of it.
Right now random string substitution replaces the whole token, it works well for cases where you need a totally random value but doesn't work when you want to only partially substitute. A good example of this is cases where you need to generate a random Route53 record set entry but the root DNS needs to be preserved.
This change is backwards compatible. If the parameter value in input is just `$[taskcat_random-string]` token, then the whole value gets replaced. When the parameter value has prefix and suffix strings, only the token gets …
> Allow partial substitution in random string tokens. 

- taskcat/stacker.py
Looking at a few different repos, it appears that the expected functionality of the `taskcat_getsingleaz` substitution differs from its actual implementation. Currently this will always return a single AZ as expected, but always the first AZ as returned from the API lookup.
This change allows template parameters to select specific AZ's by index, which seems to match the intended usage.
It appears that this was intended to allow a template's parameters to select availability zones without knowing what they are. CloudFormation provides this as a pseudo-parameter mapping, but it may make more sense to allow users to specify availability zones at launch time. In this case, taskcat needs a similar kind of mapping lookup.
For multiple examples, see the various compliance-* repos. Here's the PCI …
> Return specific AZ's for taskcat_getsingleaz

- bin/taskcat
- taskcat/generate_reports.py
- taskcat/stacker.py
This PR returns an exit code of 1 if any test fails. This ensures Taskcat is compliant with expected behavior as a standalone utility in build pipelines.
Testing done: Verified proper return code from `sample-taskcat-project`; log output below. 
Upstream dependencies: #230 #232 
```
taskcat/examples on  issues/223 [$✘!?] via taskcat-development
➜ python3 $(pwd)/../bin/taskcat -c sample-taskcat-project/ci/taskcat-autobucket.yml
(...)
[INFO   ] :AWS REGION      CLOUDFORMATION STACK STATUS [CLOUDFORMATION STACK NAME]
[INFO   ] :us-east-1       STACK_DELETED             [tCaT-tag-taskcat-json-4e431e84]
[INFO   ] :us-east-1       STACK_DELETED             [tCaT-tag-taskcat-yaml-4e431e84]
[INFO   ] :All stacks deleted successfully. Deep clean-up not required.
[INFO   ] :All stacks deleted …
```
> Ensure TaskCat returns exit code 1 if stack fails.

- taskcat/stacker.py
Reverts aws-quickstart/taskcat#247 Wrong target branch
> Revert "Little Typo fix"

- taskcat/stacker.py
This PR fixes the issue where Taskcat fails with _KeyError[Parameters]_ when 'Parameters'_ section is missing in the template. This fix will allow to use Taskcat for templates without parameters.
Tested with templates with and without parameters.
> BugFix - KeyError when testing templates with no parameters

- taskcat/stacker.py
Fixes a bug introduced with #261.
When no exclude param is provided, this exception is raised:
```
Traceback (most recent call last):
File "/Users/mfigus/.pyenv/versions/3.7.1/bin/taskcat", line 4, in <module>
__import__('pkg_resources').run_script('taskcat==0.8.27', 'taskcat')
File "/Users/mfigus/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/Users/mfigus/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
exec(code, namespace, namespace)
File "/Users/mfigus/.pyenv/versions/3.7.1/lib/python3.7/site-packages/taskcat-0.8.27-py3.7.egg/EGG-INFO/scripts/taskcat", line 101, in <module>
main()
File "/Users/mfigus/.pyenv/versions/3.7.1/lib/python3.7/site-package …
```
> Exclude bugfix

- taskcat/stacker.py
Clients accessing ephemeral buckets should always use sigv4
```
taskcat -c ci/taskcat.yml -u
ipython
In [1]: import boto3
In [2]: s = boto3.client('s3', config=boto3.session.Config(signature_version='s3'))
In [3]: s.get_object(Bucket='taskcat-tag-quickstart-redhat-openshift-b8f5dc82', Key='quickstart-redhat-openshift/templates/openshift.template')  
...
ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
In [4]: s = boto3.client('s3', config=boto3.session.Config(signature_version='s3v4'))                                                            
In [5]: s.get_object(Bucket='taskcat-tag-quickstart-redhat-openshift-b8f5dc82', Key='quickstart-redhat-openshift/templates/openshift.template')  
Out[5]: 
{'ResponseMetadata': {'RequestId': 'ttt', …
```
> disable sigv2 on ephemeral buckets by default

- taskcat/client_factory.py
- tests/unittest/test_client_factory.py
Adds the `regional_cred_map` dictionary to ClientFactory. Expects a dict in this format:
```
{
<region> : {
'aws_access_key_id' / 'profile_name' / ...
}
}
```
This is useful in environments that manage deployments across multiple accounts. Rather than run multiple seperate taskcat/amiupdater/(other tool) invocations, credentials can be customized to suit individual use-cases. 
ad-hoc tests. 
```
bpython version 0.17.1 on top of Python 3.7.3 /usr/local/opt/python/bin/python3.7
>>> from client_factory import ClientFactory
>>> regional_cred_map = {'ap-east-1':{'profile_name':'andrew-hongkong'}}
>>> from client_factory import ClientFactory
>>> regional_cred_map = {'ap-east-1':{'profile_name':'andrew-hongkong'}}
>>> cf = ClientFactory(regional_cred_map=regional_cred_map)
>>> ec2_default = …
```
> Adding regional cred granularity to ClientFactory

- bin/amiupdater
- taskcat/amiupdater.py
- tests/unittest/test_amiupdater.py
This PR adds a custom exception in the event of a template with no filters found. This exists 0, versus triggering a FatalException. The use case is for CI/CD pipelines where no filters found isn't a fatal error and the pipeline wishes to proceed further. 
Tests modified accordingly.
> AMIUpdater: Custom exception for no filters; exiting 0; tests

- taskcat/cfg/amiupdater.cfg.yml
Added product code (aw0evgkw8e5c1q413zgy5pjce) for CentOS 7 AMI. Otherwise it is pulling a newer AMI with the same name but a different code (f7hh9b6i4gjxl02w2umkoyu5)
> Added product code for CentOS 7 AMI

- requirements.txt
This updates cfn_lint from 0.13.0 to 0.23.3, so that linting works for newly supported services, such as Amazon Managed Blockchain.
I ran `python setup.py test` both before and after my changes and saw no alteration in the results. However, I am experiencing a broken test that appears to be unrelated:
test_genaz_raises_taskcat_exception (test_template_params.TestParamGen) ... [ERROR  ] :!Only 1 az's are available in us-east-1
I submitted this as Issue #321.
> Update cfn_lint dependency

- taskcat/template_params.py
- tests/unittest/test_template_params.py
Issue 335
This allows usage of `$[taskcat_genpass_8S]` random parameter for RDS password type in CloudFormation. By definition the RDS passwords can be:
> The password can include any printable ASCII character except "/", """, or "@".
- Run the tests to verify that I didn't break existing tests or functionality
- Run the function 100 times to verify that it doesn't produce a password with `@`
It is a fairly trivial change.
> Remove @ character from randomly generated passwords

- taskcat/generate_reports.py
- taskcat/stacker.py
Stop using the removed vendored `requests` lib from the `botocore` dep,
Ran my existing CI suite using taskcat.
If a run generates a report without blowing up, this did its job.
> Don't use the botocore vendored requests. Fixes #342

- .travis.yml
The pypi deploy plugin in TravisCI appears to checkout the git repository again, with a clean stage environment. While the logic around development releases is working as intended, a duplicate 0.9.0 release is attempted;
~This PR swaps out the built-in travis-ci plugin for twine commands, and allows us more granular control of the build environment.~
This PR introduces the `skip_verify` option. If that doesn't work, another PR is forthcoming.
> [travis] Disabling cleanup on travis pypi deployment step

- .travis.yml
Looking at the travis API, the "sender" in travis-ci parlance is whomever _merged the pull request_, not who opened it. 
https://api.travis-ci.org/v3/build/607854388  - under _Created By_, at the bottom.
Editing the travis logic to reflect this discovery.
This PR also moves release-tagging and documentation to their own stage;
> More revisions to travis logic

- taskcat/_template_params.py
- tests/test_template_params.py
This PR accounts for a param value being None. This occurs if there's no Default value in the template, and no parameter value is passed in. A duplicate of #395 , but I think this handles it better.
> Throwing an exception if a parameter value is None. Fixes #391

- requirements.txt
- taskcat/_lambda_build.py
- tests/data/lambda_build_with_submodules/functions/source/TestFuncPip/a_file
- tests/data/lambda_build_with_submodules/functions/source/TestFuncPip/requirements.txt
- tests/data/lambda_build_with_submodules/functions/source/TestFuncRaw/a_file
previous behavior was to skip the build step if there was no Dockerfile present. This adds two additional cases:
* `requirements.txt` present, runs a `pip install` to build deps and packages a zip
* catchall zips the contents of the source folder as is
> add pip and raw lambda package methods

- taskcat/_s3_sync.py
Adds an s3 upload exclude for the new default lambda source path `lambda_functions/source/`
> add new default lambda source pasth to the excludes

- .pre-commit-config.yaml
- taskcat/_cfn/template.py
- taskcat/_cli_modules/list.py
- taskcat/_common_utils.py
- taskcat/_dataclasses.py
- taskcat/_generate_reports.py
- tests/test_cfn_lint.py
`taskcat test list` was failing with `IndexError tuple index out of range` due to an inverted comparison
ran the following tests:
```bash
taskcat test run -n
taskcat test list
taskcat test clean ALL
###
taskcat deploy aws-vpc
taskcat list
taskcat delete <ID-FROM-LIST>
```
> fix list output

- .travis.yml
taskcat docs use mkdocs. 
pages provide does not render html correctly
> Remove travis provider (pages)

- taskcat/_cfn/stack.py
- taskcat/_cfn/template.py
boto3 claims that `get_template` returns the template body, but in some (all?) cases it returns the template as a string.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Client.get_template
Fixes #423
> TemplateBody is sometimes a string

- taskcat/_cfn/stack.py
- taskcat/_common_utils.py
- tests/test_common_utils.py
intermittently buckets that taskcat has just created raise an exception if get_bucket_location is called right after the bucket has been created. This adds retries to give the bucket some time to propagate.
Also updates the s3 url format for `us-east-1` buckets to include the region in the hostname.
> retry if we're sure the bucket exists

- .travis.yml
adds caching for pre-commit deps, pip packages and mypy stubs in the hope of speeding up pr tests.
> add caching to travis for pip/pre-commit

- assets/css/taskcat_reporting.css
Some semicolons were giving an error, others not.
Added some missing semicolons in the css file.
They are just css small fixes. Shouldn't give any error.
Also fixed a misspelled css keyword. (L. 139)
```css
border-bottom-: 1px solid #C1C3D1;
```
> Fix css missing semicolons

- taskcat/_cfn/stack.py
- taskcat/_cfn/threaded.py
- taskcat/_cli_modules/deploy.py
- taskcat/_config.py
- taskcat/_dataclasses.py
- tests/test_cfn_stack.py
This is a fix to #449, where it was reported that tags defined in the taskcat config file were not being honored.
> Honoring tags within config file. Closes #449

- taskcat/_client_factory.py
- tests/test_client_factory.py
This adds regional endpoint support for STS clients, with room for more services later, if needed.
Tests, in progress. Also spot-checks.
```
>>> from _client_factory import Boto3Cache
>>> b3 = Boto3Cache()
>>> x = b3.client('sts',region='us-east-2')
>>> x.meta.endpoint_url
'https://sts.us-east-2.amazonaws.com'
>>>
>>>
>>> x = b3.client('sts')
>>> x.meta.endpoint_url
'https://sts.us-east-1.amazonaws.com'
>>>
```
> Adding regional endpoint support for STS clients. Closes #289

- .travis.yml
This adds more granular conditions to GH releases. See #463
> More granular condition on GH releases.

- taskcat/_cfn/template.py
I know that taskcat currently is not supported in Windows but I do use it on windows and only thing which currently stops me using it on windows is it creates wrong s3 URL for template after uploading it on s3 due to windows path format.
Eg. c:\user\project\template\my-template.yml when uploaded on s3, URL becomes https://s3.console.aws.amazon.com/s3/object/your-bucket-name/cf-project/templates\my-template.yml and hence give error that it is not correct s3 bucket URL.
In above example correct URL should be, https://s3.console.aws.amazon.com/s3/object/your-bucket-name/cf-project/templates\my-template.yml
I have run above change in my windows machine as well on mac to make sure it works
> Converting path to posix style to prevent error on windows

- examples/sample-taskcat-project/templates/debug.template
- taskcat/_cli_modules/test.py
- taskcat/_config.py
- tests/test_config.py
This PR slightly changes the logic in the test subcommand. Previously the `s3_enable_sig_v2` config option was being force-passed as a CLIArgument to a Config object. As CLI arguments are processed last in the Config class, setting `s3_enable_sig_v2: True` in either the global or project config file was ignored. 
I've tested this using a debugger with the sample taskcat project in `examples/`. Unit tests and pre-commit checks have been run as well. 
I think there's a better way to handle the logic introduced in the test CLI module, but the linters/checks in pre-commit were not happy at me.
> Refactoring S3 SigV2 CLI Argument in test subcommand

- .travis.yml
This PR switches our versioning library to the newer `packaging.version`; This will properly preserve release ordering - 0.9.13.dev0 is newer than 0.9.12. 
https://stackoverflow.com/a/11887885
I've dry-run the logic herein.
> Proper ordering for version numbers. Closes #465

- taskcat/_config.py
- tests/test_config.py
As reported in #434, taskcat was not honoring values set via...
```
auth:
default: foobar
```
The intention of the original code was to honor the regional-based profile settings first, then the default profile settings, then set 'default' if necessary. Instead, we checked for regional profile settings, then skipped directly to 'default'. 
Tests are included, and passing.
> Honoring default profile value. Closes #434

- taskcat/_template_params.py
- tests/test_template_params.py
This PR adds support for a list as a parameter value. Tests are included.
> Supporting lists as a parameter value. Closes #443

- taskcat/_cfn/threaded.py
- taskcat/_cli_modules/test.py
- taskcat/_config.py
- taskcat/_dataclasses.py
- taskcat/cfg/config_schema.json
- tests/test_config.py
Solves #360. Important for projects where the stack names cannot be too
long because some AWS services will use the stack name as a default
resource name prefix and this might be too long when using nested stacks.
No tests added.
Default behavior is the same as before.
Add `shorten_stack_name: true` to the `taskcat.yaml` file and see that the stack name is going to be like: `tCat-testName-abc123`
> Add shorten_stack_name project parameter

- requirements.txt
These two dependencies are shared by aws-sam-cli, which is commonly installed in the same virtualenv as taskcat (testing sam templates), so should not have conflicting version requirements.
> update pyyaml and docker deps

- taskcat/_client_factory.py
- tests/test_client_factory.py
This PR adds `import_session` to Boto3Cache, storing the session as a profile within the cache with a special prefix (imported_session). The prefix is added so that there's no namespace collisions between `imported_session_default` and `default`. 
If users want a standard profile (`default`, `us-east-1`, etc), they'll need to leverage the existing profile methods as previously documented.  
The intention here is to allow flexibility when importing the class in from-scratch modules (outside of taskcat).
The current cache only supports profiles. That works great for taskcat itself, and we've previously made design decisions to this effect.
However, it excludes in-memory credentials, such as those fetched from SecretStore, or via STS.AssumeRole. Without the ability to import an …
> Adding import_session to Boto3Cache; plus tests.

- taskcat/_cli_modules/test.py
- taskcat/_common_utils.py
- taskcat/_config.py
- taskcat/_dataclasses.py
- taskcat/cfg/config_schema.json
- tests/data/config_inheritance/.taskcat_global.yml
- tests/data/regional_client_and_bucket/.taskcat_global_regional_bucket.yml
- tests/test_config.py
_Continuation of #456. This is being reopened to resolve a coverage issue_
Part of the SigV2 -> SigV4 saga. This is necessary to facilitate SigV4 regional buckets. Initially, it'll create *more* buckets per test (1 per region), but those buckets will be retained (emptied if necessary). 
New buckets will be auto-created in this format:
`taskcat-<account_id_hash>-<region_name>`.
_Note: No modifications to `$[taskcat_autobucket]` are necessary due to the current design_
Special things to consider:
- This is opt-in via `s3_regional_buckets` from global down to test-level.
- Please pay special attention to these functions:
Dataclasses:
- generate_bucket_name,
- generate_regional_bucket_name,
Config:
- _create_regional_bucket_obj
- _create_legacy_bucket_obj
> Opt-in regional S3 buckets.

- taskcat/_client_factory.py
- tests/test_client_factory.py
This PR changes how we determine what the partition for an account is. Old method relied on boto3.client.get_available_regions('s3'); which does not implicitly return cross-partition data. 
new method is to iterate over partition and default region until an `sts.get_caller_identity()` call succeeds. 
Unit tests are included. 
Unit tests
actual live testing.
> Accurately determine the appropriate partition for an account. Closes #503

- taskcat/_client_factory.py
This was overlooked in the previous commit w/r/t imported sessions. This change returns the correct default region when Boto3Cache.client (and others) are called with an `imported_session_*` profile. 
Unit tests. Manual testing. Ran through E2E.
> [ClientFactory] Accounting for imported sesssions in get_default_region

- taskcat/_cfn/template.py
This PR fixes the `url_prefix` to remove the region from the URL when it's available, because a main use-case of this property is to prefix match against child stacks gathered from update events, where they arrive without the region in their URLs.
No tests added.
Solves #487 
Testing the fix requires using doubly nested stacks to reproduce #487. Stacks that don't have nesting shouldn't see different behavior.
> Remove region from url when computing url prefix

- taskcat/_client_factory.py
- tests/test_client_factory.py
This PR removes previously-added functions to client factory. They're no longer necessary and were added for an edge-case that was better handled out of band.
> removing import_session

- CODEOWNERS
- taskcat/_template_params.py
- tests/test_template_params.py
This PR adds the `$[taskcat_current_region]` magic parameter. It returns the region passed into the ParamGenerator class. 
Unit tests. Live tests.
```
BucketRegion | us-east-2
-- | --
```
> Adding $[taskcat_current_region] magic parameter.

- taskcat/_cfn/stack_url_helper.py
- tests/test_stack_url_helper.py
This is a fix for #514. It increases the recursive nesting limit to 20.
Ran new unit tests.
Ran end to end tests.
n/a
> Increase nesting restrictions on StackUrlHelper from 6 to 20

- .pre-commit-config.yaml
- taskcat/_cfn/stack.py
- taskcat/_cfn/stack_url_helper.py
- taskcat/_cfn/template.py
- taskcat/_common_utils.py
- taskcat/_config.py
- taskcat/regions_to_partitions.py
- tests/test_common_utils.py
- update_partition_region_map.py
This addresses concurrency/scale issues identified when a project has broad region coverage, multiple tests, and `s3_regional_buckets: true`. 
Each template file in a project would be opened and read from the filesystem tests*regions*number_of_uses_as_child times. 
an ssm client was also created every time an s3url needed to be resolved, this is now done using a static mapping that is auto-updated via pre-commit.
Also, the recent template parsing addition has added several debug log statements that print values, imho these could be best obtained from an interactive debugger when troubleshooting and shouldn't be in taskcat outputs.
> cache cfnlint template objects

- taskcat/_config.py
With the blanket exception catching a project with an invalid new-style config and a valid legacy config would end up running the legacy config.
Legacy config should only be looked for if the new-style does not exist.
> only look for legacy config if new style one is not found

- taskcat/_cli_modules/package.py
The package command should not do anything if the project has explicitly disabled packaging in config with `package_lambda: false`.
> only package if config allows

- taskcat/_dataclasses.py
Leverages `self.partition` to provide appropriate partition information to the SigV4 bucket policy. 
Previous was hard-coded to `arn:aws:<snip>`.
- unit tests
- realtime tests (launched a test in aws-us-gov)
> Supporting multiple partitions in S3 SigV4 bucket policy. Closes #533

- taskcat/_cli_modules/test.py
this pr introduces a `test retry` command.
When working on projects with nested templates and long launch time it costs a lot of time to-re-launch tests when an inner stack fails, because all of the successful resources that preceded the failed stack need to be needlessly re-launched.
Example usage:
```bash
cd quickstart-linux-bastion
taskcat test run -n
taskcat test retry eu-north-1 tCaT-quickstart-linux-bastion-amznlinux2hvm-xxx BastionStack
```
this will get the parameters fed to the Bastion stack in the failed launch, delete BastionStack child stack, before uploading your updated project and re-launching the child stack with the same parameters. So the VPC does not need to be torn down and rebuilt to test your changes.
ran it against the linux-bastion and eks quick starts.
> add test retry command to re-stage and re-launch an inner stack

- taskcat/_cli_modules/deploy.py
- taskcat/_cli_modules/lint.py
- taskcat/_cli_modules/test.py
- taskcat/_cli_modules/update_ami.py
- taskcat/_config.py
- tests/test_amiupdater.py
- tests/test_cfn_lint.py
- tests/test_cfn_stack.py
- tests/test_cfn_template.py
- tests/test_cfn_threaded.py
- tests/test_config.py
Moving project_root to the Config obj as a convienience method. It helps cut down passing around a project root where needed. 
Tests throughout. Ran it on a project.
> Moving project_root as an attribute to config object; plus tests throughout. Closes #540

- taskcat/_cli_modules/test.py
Extracted the output-directory argument from @andrew-glenn's draft PR #555 
This PR adds `--output-directory` to `taskcat test run`
Manual testing
This change was pulled from the draft PR by @andrew-glenn since that PR failed e2e tests and cannot be merged until all of its features are working (`--profile`, decorators). This single argument is a simpler change which can be merged separately.
1. Run taskcat with defaults: `taskcat test run`. Expected outcome: reports are generated in `./taskcat_outputs`
2. Run taskcat with argument: `taskcat test run --output_directory ./build/taskcat`. Expected outcome: reports are generated in `./build/taskcat`
> Adding --output-directory; Closes #266

- taskcat/_amiupdater.py
- taskcat/_cli_modules/update_ami.py
- tests/test_amiupdater.py
Handling region reconcilation within the update-ami (well, _amiupdater) module has been not-ideal. 
This PR refactors the relevant module functions to..do..better. 
unit tests. 
live tests.
_Caveat_ This PR is dependent on #543
> Better region/profile handling for update-ami subcommand

- taskcat/_cli.py
- taskcat/_cli_core.py
- taskcat/_cli_modules/test.py
- tests/test_cli.py
- tests/test_cli_core.py
This PR...
~~- adds `--output-directory` to `taskcat test run`~~
- adds `--profile` as a root-level parameter. (Ex: `taskcat --profile foo test run`)
- honors `package_lambda: false`
- Adds decorators that allow us to further customize the argument behavior. 
Adding `--profile` as a root-level argument means that it's passed to every subbcommand module. For now, simply adding `*_args, **_kwargs` to each module class settles it. However, this means that each subcommand may behave differently. We may want to centralize a bare-bones config object (OR - args) to pass-through so that when a new subcommand is added, it's not missed. 
Would very much appreciate feedback on this caveat, as it directly impacts another PR that …
> Batched addition of arguments throughout.

- taskcat/_cfn/_log_stack_events.py
- taskcat/_cli_modules/test.py
- taskcat/_tui.py
add 2 flags to `test run` subcommand:
`--minimal-output` flag doesn't use the terminal printer, and only prints stack status when it changes. output looks like:
```
[INFO   ] : monitoring-prom-graf ap-southeast-2 CREATE_IN_PROGRESS
[ERROR  ] : monitoring-prom-graf ap-southeast-2 CREATE_FAILED
[ERROR  ] :     GrafanaHelmChart AWS Error: ResourceConflictException - Function already exist: helm-provider-vpc-connector-8c1f98b277d5eed33a85f2dc07e4c71c <nil>
[INFO   ] : monitoring-prom-graf ap-southeast-2 DELETE_IN_PROGRESS
[INFO   ] : monitoring-prom-graf ap-southeast-2 DELETE_COMPLETE
```
`--dont-wait-for-delete` flag calls delete_stack and then exits without waiting to see if stack delete is successful.
> add minimal-output and dont-wait-for-delete flags

- taskcat/_cli_modules/__init__.py
- taskcat/_cli_modules/test.py
- taskcat/_cli_modules/upload.py
- taskcat/_config.py
- taskcat/_lambda_build.py
- taskcat/_s3_stage.py
- tests/test_cli_module_test.py
two changes here:
* adds `taskcat upload` command that uploads to s3, but does not run tests. Fixes #547
* adds `--skip-upload` to `taskcat test run` that does not upload anything to s3
This facilitates the following use-cases:
*use as an uploader/publisher* - taskcat can now be used to publish to s3
*test already staged projects* - can test projects previously staged, taskcat as a canary
Consider the following project config:
```
project:
name: quickstart-amazon-eks-develop
template: templates/amazon-eks-master.template.yaml
s3_bucket: aws-quickstart
parameters:
RemoteAccessCIDR: 10.0.0.0/16
QSS3BucketName: aws-quickstart
QSS3KeyPrefix: quickstart-amazon-eks-develop/
AvailabilityZones: $[taskcat_genaz_3]
tests:
default-entrypoint:
s3_regional_buckets: false
regions:
- us-east-1 …
```
> facilitate decoupled upload and test

- taskcat/_cfn/stack_url_helper.py
- taskcat/_cfn/template.py
The previous invocation method of StackURLHelper didn't pass in any parameters for the template. The net-result was that StackURLHelper didn't replace template parameters in a URL with (at minimum) their default values. 
Note: There's still an outstanding issue where we don't pass in the parameter values but this solves my immediate issue.
> Invoking StackURLHelper so that it replaces variables with parameters

- taskcat/_common_utils.py
In the case where you are testing with `--skip-s3-upload` the bucket objects are hosted in may be different to where you are running tests. This enables that.
Note that this will only work for public buckets in the `aws` partition, as an unauthenticated http get is required, and we can't guess the partition.
> try to get bucket location from http headers if AccessDenied

- taskcat/_amiupdater.py
- taskcat/_cli_modules/update_ami.py
- tests/test_amiupdater.py
Makes update-ami work across partitions and accounts in defined in global config `auth`.
Also allows filter values to be lists so, for example, you can specify multiple `owner-id`'s.
Ran it against linux bastion and eks quick starts
> update-ami across partitions

- taskcat/_cfn/threaded.py
- taskcat/_common_utils.py
- taskcat/_config.py
- taskcat/_dataclasses.py
- taskcat/_template_params.py
- tests/test_dataclasses.py
- tests/test_template_params.py
- Adding "$[taskcat_project_name]" and "$[taskcat_test_name]". Closes #550
- Fixing AZ Blacklist passthrough; Closes #551 
- Adds SecretsManager support; Closes #530 Closes #581 
- Adds support for fixed stack name, stack prefix, stack suffix.
Plus unit tests.
> Batch Bug Fixes and Feature additions

- e2e/tests/lint.sh
- taskcat/_amiupdater.py
- taskcat/_cfn/stack.py
- taskcat/_cfn_lint.py
- taskcat/_cli_modules/test.py
- taskcat/_client_factory.py
- taskcat/_common_utils.py
- taskcat/_config.py
- taskcat/_dataclasses.py
- taskcat/_s3_sync.py
- taskcat/cfg/config_schema.json
- tests/test_cfn_lint.py
- tests/test_cfn_threaded.py
This PR...
- Addresses a race condition where an out-of-band action against a stack could result in a successful test (Issue #195 - originally marked as wontfix, now fixed)
- Identifies a `DELETE_FAILED` status as a stack failure. (#531)
- Improves how linting errors are displayed to the end user. (screenshot attached)
- also adds support for the new LAX local zone.
_plus unit tests_
> More stringent critera for successful tests, cosmetic improvment to linting behavior

- taskcat/_amiupdater.py
Currently runnig the command:
```bash
taskcat update-ami
```
under python 3.6 fails with an exception.
Complaining that the constructor of the dataclass RegionObj is missing a value.
I run the same command before the fix and after the fix to make sure it is running. this change only affect update-ami.
I have not changed or created a test case for this as I assumed there is a reason why it was not tested as part of data classes.
> add missing argument to constructor

- e2e/pr_bot/handler.py
Fixes PR Bot so it works on `main` versus legacy `master`. Single line change.
> PR Bot: Master => Main

- taskcat/_s3_sync.py
- tests/test_amiupdater.py
When taskcat's s3 uploading was created boto3 only did single threaded uploads. Adding boto3/s3transfer's threading implementation on top of what's in taskcat results in waay too many threads being spawned for a big project with many regions. 
Ultimately we should evaluate the s3transfer implementation and use that instead of our own threads, for now though this fixes the implementation for large projects.
tested upload of eks quickstart, which prior to this patch crashed my macbook.
> disable boto3 s3 threading

- taskcat/_dataclasses.py
- taskcat/cfg/config_schema.json
A super simple PR to add support for regions in the global/general config. 
Use case is situations where the regions defined in the project config wish to be unilatery overwritten. I don't expect that this will gander much use, however edge cases have cropped up where this will be very useful.
pre-commit hooks ran, unit tests ran.
> Adding regions to global config

- taskcat/_cli_core.py
- taskcat/_cli_modules/upload.py
- taskcat/_s3_stage.py
- taskcat/_s3_sync.py
This PR:
- Adds `--key-prefix` and `--dry-run` (longform required) to `taskcat upload` subcommand
- Fixes a bug in `CliCore.longform_param_required` that affected CLIModules that were classes (Upload, for example)
NOTE: `CliCore.longform_param_required` was not in use previously, so the bug was not encountered.
The use-case for dry-run is pretty edge, but in conjunction with `key-prefix`, it may be desirable to see the effects without uploading. 
The upload logic and logging messages have been modified to reflect this flag. All other operations - object comparision, flagging for delete, and so on, still exist.
The net-result is that the user will see what objects are being uploaded/deleted, without the upload/delete actually occuring.
> Adding key_prefix and dry_run to upload subcommand

- README.md
A quick documentation edit for advanced use cases of AWS creds. Closes #596
> Docs: non-standard credentials

- .pylintrc
- .travis.yml
- e2e/tests/test_import.sh
- setup.cfg
- setup.py
- taskcat/_dataclasses.py
- taskcat/cfg/config_schema.json
- taskcat/testing/_cfn_test.py
- taskcat/testing/_hooks.py
- taskcat_plugin_testhook/__init__.py
- tests/data/hook_plugin/.taskcat.yml
- tests/data/hook_plugin/templates/test.template.yaml
- tests/testing_module/test_hooks.py
This PR adds a pluggable way to add hooks that run before or after stacks are launched. Plugins receive test definitions, taskcat config object and rendered parameters, with stack outputs coming in a future pr.
example project config using plugins:
```
tests:
foobar:
prehooks:
- type: cfn-lint
config:
strict: true
custom-resource-spec: ./my-resource-spec.json
posthooks:
- type: run-command
config:
command: touch blah
timeout: 100
```
plugins must be installed using the `type` prefixed with `taskcat_plugin_` as package name, and `Hook` as class name. These can be bundled into taskcat when it installs, or installed separately from a plugin owned and published by 3rd parties.
> hook plugin implementation

- taskcat/_lambda_build.py
Seeing this failure when a nested submodule contains a file in `<submodule_path>/functions/source/`. It is only expecting directories there.
> lambda build should ignore files and only process directories

- docs/README.md
Build was moved to travis-ci.com. Update the badge URLs accordingly.
> Migrate travis-ci URL in documentation

- taskcat/cfg/amiupdater.cfg.yml
Signed-off-by: David Duncan <davdunc@amazon.com>
This adds support in the AMI Configurator for RHEL 8.3 with High Availability and RHEL 8.4 with High Availability  so that the images can be updated when new images are released. 
Images IDs were matched using the filters in aws cli calls to confirm that they provide the desired results. 
By verifying that the filters are valid and return the intended results. 
```bash
$ aws ec2 describe-images --filters "Name=name,Values=RHEL_HA-8.3_HVM-????????-x86_64-?-Hourly2-GP2" "Name=owner-id,Values=309956199498" --region us-east-1 --query 'Images[].{Name:Name,AMI:ImageId}'
[
{
"Name": "RHEL_HA-8.3_HVM-20210315-x86_64-1-Hourly2-GP2",
"AMI": "ami-03e95cf9553d62e4e"
}
]
$ aws ec2 describe-images --filters …
```
> Add amiupdater support for RHEL 8 with HA images

- taskcat/_cfn/stack.py
- tests/test_cfn_stack.py
Fixes #660 
The [criteria_matches](https://github.com/aws-quickstart/taskcat/blob/2072dd5182afe7a260cb7d6e2af132ee09490fb5/taskcat/_cfn/stack.py#L28) function used `foo.__dict__` to look for instance attributes when filtering out items. This worked until the `Stack` class changed its `status` attribute to be a property instead. Turns out that properties behave like class attributes and not instance attributes???
I wrote a test case to replicate the bug and then fixed it.
Other than a unit test, I didn't but I was hoping @tekdj7 would test against this branch and confirm it works. If not I might try it out locally.
Do we have a functional test where we create two or three stacks and make one fail. Where we actually use --keep-failed and then we …
> Fix: --keep-failed throws exception

- taskcat/_cli_core.py
```
❯ taskcat test
_            _             _
| |_ __ _ ___| | _____ __ _| |_
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_
\__\__,_|___/_|\_\___\__,_|\__|
version 0.9.23
usage: taskcat [args] test [args] [subcommand] [args]
taskcat [args] <command> [args] [subcommand] [args] test: error: the following arguments are required:
```
```
❯ taskcat test
_            _             _
| |_ __ _ ___| | _____ __ _| |_
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_
\__\__,_|___/_|\_\___\__,_|\__|
version 0.9.23
error: the following arguments are required:
usage: taskcat [args] test [args] [subcommand] [args]
Performs functional tests on CloudFormation templates.
optional arguments:
-h, --help  show this help message and exit
subcommands:
clean - tests
list - …
```
> Making argument errors spit out help text

- setup.py
The previous PR (#692) did not include the newly-created directory `iam_policy` in packaging. This lead to false-positives when testing.
> [BUGFIX] Adding iam_policy to python packaging

- CODEOWNERS
- taskcat/_cfn_lint.py
This change excludes submodules from linting actions. The user typically has no control over submodules and it's not a fair user experience to fail linting based on code that's out of scope.
> Exclude submodules from lint mechanisms. Closes #701

- pyproject.toml
Change `favicon` and `logo` to tcat.png to render png logo
Currently the website shows that the logo and the favicon are unavailable:
Whereas [Portray](https://timothycrosley.github.io/portray/) can display both if the values are set correctly to existing links
From the `assets/docs/images` directory there is also the `logo.png` image. I think it's the same as `tcat.png`. Since the main GitHub README uses `tcat.png` I opted to do the same
> docs: fix links to favicon, logo to tcat.png

- taskcat/_dataclasses.py
- taskcat/cfg/config_schema.json
Just a quick PR to modify the `project.name` regex validation to allow a forward slash.
> key prefix validation

- taskcat/_config.py
- taskcat/_template_params.py
- tests/data/git_branch_without_repo/.taskcat.yml
- tests/test_template_params.py
A new use-case has emerged where passing in the current git branch as a parameter is desirable. 
Therefore, this PR introduces the `$[taskcat_git_branch]` psuedo-parameter. Unit tests are included. If the psuedo-parameter is used in a project root that's not a git repo, and exception is raised.
> New Psuedo Param: [taskcat_git_branch]

- requirements.txt
dataclasses-jsonschema v 2.15.2 results in a typeerror; limiting install to 2.15.1 is a workaround for now.
> Requirements pinning

- taskcat/cfg/amiupdater.cfg.yml
Related to https://github.com/aws-quickstart/quickstart-linux-bastion/pull/176
> Add AMI updater support for Ubuntu Server 22.04 LTS and SLES 15 SP4

- THIRD_PARTY
- requirements.txt
- taskcat/_s3_sync.py
This PR introduces the `pathspec` library to handle s3 excludes via the gitignore syntax.
> Migrating to pathspec (gitignore syntax) method for excludes

- taskcat/testing/_cfn_test.py
This is related to the issue mentioned [here](https://github.com/aws-ia/taskcat/issues/743) when you run taskcat without a valid test it simply exists
Added a warning message about missing tests 
Ran test locally and verified the changes
```
taskcat -d --profile ... test run -t foo,bar,baz
_            _             _   
| |_ __ _ ___| | _____ __ _| |_ 
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_ 
\__\__,_|___/_|\_\___\__,_|\__|
version 0.9.36
[WARN   ] : No valid test found.
```
_Edit by @andrew-glenn: Closes #743_
> Show message on terminal before exiting -- Add a message about missing test

- requirements.txt
This PR bumps the minimum cfn-lint version to include nodejs18.x lambda runtime support.
See this closed issue from the cfn-lint repo for more information: https://github.com/aws-cloudformation/cfn-lint/issues/2494.
Installed and built locally.
n/a
Attempt to lint a template which includes a lambda with the following runtime:
`Runtime: nodejs18.x`
and you should not receive the following error:
`[Check if properties have a valid value] You must specify a valid value for Runtime (nodejs18.x). Valid
values are ["dotnet6", "dotnetcore1.0", "dotnetcore2.0",
"dotnetcore2.1", "dotnetcore3.1", "go1.x", "java11", "java8",
"java8.al2", "nodejs", "nodejs10.x", "nodejs12.x", "nodejs14.x",
"nodejs16.x", "nodejs4.3", "nodejs4.3-edge", "nodejs6.10",
"nodejs8.10", "provided", "provided.al2", …
> Bump cfn-lint minimum version to add nodejs18.x lambda runtime support

- taskcat/_config.py
- taskcat/testing/base_test.py
- tests/testing_module/test_base.py
… unittests
Addressing the issue mentioned [here](https://github.com/aws-ia/taskcat/issues/662) . When passing a template file it fails
`taskcat test run -i TestTemplate.yaml. I get [Error] : ConstructorError could not determine a constructor for the tag '!Ref'`  
Ran the following tests
` taskcat --profile ${AWS_PROFILE} test run -i Template_file.yaml`
` taskcat --profile ${AWS_PROFILE} test run`
` taskcat --profile ${AWS_PROFILE} test run -i .taskcat.yml`
_Edit by @andrew-glenn: Closes #662_
> Detect if inputfile is taskcat config or CloudFormation template, Add unittests

- taskcat/_config.py
_Edit by @andrew-glenn: Closes #780_
This is related to the issue documented [here](https://github.com/aws-ia/taskcat/issues/780) 
I created a empty `.taskcat_overrides.yml` file and tested multiple templates. 
*  ```
taskcat -d --profile ${AWS_PROFILE} test run 
_            _             _   
| |_ __ _ ___| | _____ __ _| |_ 
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_ 
\__\__,_|___/_|\_\___\__,_|\__|
version 0.9.36
[INFO   ] : Linting passed for file: /Users/ramacjay/source/tfc/cfn101-workshop/code/solutions/conditions/condition-output.yaml
[S3: -> ] s3://tcat-linting-and-testing-workshop-rrrr/condition-output/condition-resource-property.ya …
```
> Empty taskcat_overrides.yml file -- Check if override_params is None

- taskcat/_dataclasses.py
This PR allows the `role_arn` property to propagate down from `project`. 
Closes: #618
> Adding: `role_name` to list of inherited items so propagation works

- docs/usage/GENERAL_USAGE.md
This PR fixes the schema URL in `GENERAL_USAGE.md`, pointing it to the right location.
I wasn't able to test it locally since I'm not sure how to build the docs page.
None.
None.
> Fixing schema documentation URL in GENERAL_USAGE.

- taskcat/_cli_modules/test.py
- taskcat/_cli_modules/upload.py
Noticed **taskat** instead of **taskcat** in `test run`, `test retry` subcommands and `upload` commands.
re-run the command output the correct name after this trivial modification
> Minor typo in some commands help

- .pre-commit-config.yaml
- .pylintrc
- pyproject.toml
- requirements.txt
- taskcat/_cfn_lint.py
- tests/test_cfn_lint.py
- travis-specific-requirements.txt
Widens the dependency range for cfn-lint to include the latest 1.x releases for #838. 
Assuming existing test suite would pick up any incompatibilities with the newer versions.
This has been tested by installing pinned versions of cfn-lint for 0.80.1, 1.3.1 and the latest 1.16.0, and running pytest each time. An incompatibility was found with the first non-pre-release 1.x version (1.3.0), as it seemed to be missing the method to actually run checks (I'm assuming that was a regression). 
Although I did have trouble running these locally initially - I think I'm just missing something and possibly the contributor guide needs updated to include steps to ensure the local environment is configured correctly and tests run locally. 
How to test this PR Start after checking out this branch …
> fix(deps): upgrade cfn-lint range #838

- taskcat/regions_to_partitions.py
- Updated regions_to_partitions.py to include ap-east-2 region mapping
- Fixes 'cannot find the S3 hostname for region ap-east-2' error
- Added ap-east-2 to both REGIONS dictionary and PARTITIONS['aws'] list
- All existing tests pass, region mapping functionality verified
Resolves issue with S3 hostname resolution for ap-east-2 region.
Brief description of what this PR does, and why it is needed (use case)? This fixes [GitHub issue #861](https://github.com/aws-ia/taskcat/issues/861)
N/A
> fix: Add support for ap-east-2 AWS region
