aws-ia/taskcat

taskcat/taskcat.py
Add functions to collect stack resources
=> Add functions to collect stack resources

scripts/taskcat, setup.py
=> Add taskcat cli tool to executable path

beautycorn.py
In the future we can wrap all the JSON handling into a CFNJSONHandler class (like CFNYAMLHandler) and have a higher order class that can be CFNHandler have format agnostic load and dump (plus any other things we want to beautify).
=> Porting of Beautycorn

alchemist.py, setup.py, taskcat/deployer.py, taskcat/stacker.py, taskcat/utils.py
This is really a started port. It is fully functional, but will need changes when ClientFactory becomes BotoPool.
We also need to possibly move the aws_quickstart_s3_key_prefix_builder function out to a common utils, as well as a perfected version of aws_api_init (also after BotoPool).
=> Porting of Alchemist

taskcat/stacker.py
This adds additonal parameter value generation for params which were missing in taskcat, for parity with alfred.
Following are the changes:
- Added missing parameter values check.
- Added ignorecase for regex matching
- Separated out the parameter value generation to its own method.
=> Parameter value generation - parity with alfred

installer/docker-install-master, installer/dockerfiles/fedora-master/Dockerfile
- Updated Installer
- Updated Docker Container
=> Adding alchemist to taskcat docker container

taskcat/stacker.py
Fix issue, where process exits when describe event call fails before writing log to a file hence interrupting the cleanup process
=> Fix issue32

taskcat/stacker.py
Modified create_stack behavior to first create_change_set and then execute_change_set
=> PR to handle stacks with serverless transforms

taskcat/stacker.py
This reverts commit dce8a117f662ac59c2bd7768d4556935664368cb.
=> Fix needed to address regression in #104.

taskcat.py, taskcat/stacker.py
=> Adds --version -V (Prints Version with no banner)

.github/ISSUE_TEMPLATE/bug_report.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, README.md
Added:
- PULL_REQUEST_TEMPLATE
- CODE_OF_CONDUCT
- CONTRIBUTING GUIDE
- ISSUE_TEMPLATE/bug_report.md
=> Add opensource guidelines

README.md, examples/sample-taskcat-project/ci/taskcat.yml
=> Update to example taskcat.yml

.travis.yml, tests/unittest/test_cfn_logutils.py
adds tests for cfn_logutils
ran the tests, they passed
provides 81% coverage for cfn_logutils.py
`python setup.py test`
=> tests for cfn_logutils

.bumpversion.cfg, .travis.yml, requirements.txt, setup.py, taskcat/stacker.py, taskcat/utils.py
Switch to yaml.safe_load call in stacker and utils
Longer term we should consider switching to `ruamel` or other yaml processor
=> Switch to yaml.safe_load calls

taskcat/stacker.py
=> Forcing lowercase bucket names. Fixes #155

taskcat/stacker.py
Fixes https://github.com/aws-quickstart/taskcat/issues/168
=> Fix for deep_cleanup

tests/unittest/test_cfn_lint.py
Add tests for cfn_lint, gives 86% coverage
=> add unit tests for cfn_lint

taskcat/stacker.py
Fixes: https://github.com/aws-quickstart/taskcat/issues/194
Also fully resolves https://github.com/aws-quickstart/taskcat/issues/168
=> Fixes deep cleanup

examples/sample-taskcat-project/ci/taskcat_project_override.json, taskcat/stacker.py, taskcat/template_params.py, tests/unittest/test_template_params.py
A refactor of parameter generation. Unit Tests have been added that verify, among other things: 
- All Regular expressions match the placeholder they're intended.
- No regular expressions are added without a unit test.
- Wrapper functions are tested.
- Parameter generation function is tested.
Fixes #149 ;
Potentially supersedes: #224
=> Refactor Parameter Generation

taskcat/stacker.py
This PR modifies the override behavior to match the original intent. 
- Old behavior: Function searched the template to ensure parameter could be overridden.
- New behavior: Function searches provided parameters to ensure parameter can be overridden.
Upstream dependency: #230 
Downstream Dependency: #234
=> Modifying override functionality to reflect original intent

README.md, bin/taskcat, taskcat/stacker.py, tests/unittest/test_cfn_lint.py
This PR removes the requirement that taskcat is invoked from one directory higher than <project_directory>. 
Unit Tests and Functional Tests pass.
=> Removing dependency on execution directory

bin/taskcat
Bug fix #244 
Ran test locally with the project name ending with ci
=> Bug fix #244

taskcat/stacker.py
=> Little Typo fix

bin/amiupdater, setup.py, taskcat/stacker.py
This PR adds scaffolding for future feature releases.
=> Adding scaffolding for future feature releases

bin/amiupdater, requirements.txt, taskcat/amiupdater.py, tests/unittest/test_amiupdater.py
This PR adds exit codes for AMIUpdater. This allows AMIUpdater to be used in CI/CD pipelines.
=> Exit codes for AMIUpdater.

taskcat/amiupdater.py, tests/unittest/test_amiupdater.py
This PR removes the hard-coded template key. See #297
=> [AMIUPDATER] Removing hard-coded template antipattern

taskcat/stacker.py
The current implementation of S3 bucket creation plus tagging has a reproducible issue:
```
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket)
when calling the PutBucketTagging operation: The specified bucket does
not exist
```
This happens because the bucket we try to tag doesn't exist yet.
The changed code uses a bucket_exists waiter to determine if the bucket
exists which fixes the above mentioned behavior.
- Battlefield tested
- Ran unit tests 
* run taskcat with tagging 
* taskcat -c ./test.yml -t Test=test
* taskcat shall run without any error, S3 bucket shall have the above mentioned tag
=> Use wait logic to create taskcat S3 auto_bucket

.travis.yml
This PR adds logic to auto-close Release pull-requests via Travis CI.
=> Adding adjustments to Travis CI

taskcat/amiupdater.py
This PR addresses #330 and #296
=> AMIUpdater Bug Fixes

README.md
just corrects a bit of bad grammar in the readme
NA
quite irrelevant honestly
NA
=> bad grammar

taskcat/_cli.py, taskcat/_config.py, tests/test_client_factory.py, tests/test_config.py
additional tests for `Boto3Cache` and `Config`
=> Additional test coverage

.travis.yml
This PR properly handles the dev release workflow.
0.1.0 -> 0.1.1.dev0
0.1.1.dev0 -> 0.1.1.dev1
0.1.1.dev1 -> 0.1.1
=> Updating TravisCI Config to reflect build pipeline desired state

taskcat/_dataclasses.py, taskcat/cfg/config_schema.json, tests/data/create_no_params/.taskcat.yml, tests/data/create_no_params/templates/test.template.yaml, tests/test_config.py
Allows tests that do not containp parameters
Fixes #355
=> allow undefined parameters section in test. Fixes #355

taskcat/_template_params.py
=> Add support for floating point parameters

.travis.yml
This PR refines the logic in the travis PR. This is working as intended in my fork, and reaches the pypi deployment section.
=> Fixing if-statement in travis config

taskcat/_cli_modules/test.py
adds `-k|--keep-failed` flag to `taskcat test run` command. Enabling flag will result in all failed stacks being retained, successful ones will be deleted.
Fixes: #354 
Fixes: #285
=> Adding flag to keep only failed stacks

taskcat/_config.py, taskcat/_legacy_config.py
=> support legacy global overrides from ~/.aws/taskcat_global_override.json

.travis.yml
An update to the travis regex.
=> Updating Travis regex; closes #370

.travis.yml
Remove commit_message checks from providers (trigger on tags instead)
=> Simplify travis logic based on tags

requirements.txt, taskcat/_cli.py, tests/data/standalone_template/test.template_no_tc_meta.yaml, tests/data/standalone_template/test.template_tc_empty_meta.yaml, tests/data/standalone_template/test.template_tc_full_meta.yaml, tests/test_cli.py, tests/test_common_utils.py, tests/test_config.py
adds some additional tests.
also removes `pyfiglet` dependency
=> More tests

tests/test_cli_module_test.py
a starter test for the `test` cli module.
=> initial unit test for `test` cli module

assets/css/taskcat_reporting.css
Fixes: https://github.com/aws-quickstart/taskcat/issues/383
=> Add missing css stylesheet to reports

taskcat/_cfn/stack.py, taskcat/_common_utils.py
=> correctly parse remote templates. Fixes #366

taskcat/_cfn/stack.py, taskcat/_cfn/template.py, tests/test_cfn_stack.py
=> Consistent template.url against region s3_bucket name.

.travis.yml
=> Enable github and pypi release after tagging

taskcat/_lambda_build.py
fixes pip install for lambda build under python 3.6
=> support python 3.6

.travis.yml
=> Remove tag check on pypi and github release

taskcat/_cfn/template.py
Fixes #432 
Also removes a small duplicate code fragment
=> Nested intrinsic functions cause unhandled exception

taskcat/_dataclasses.py, taskcat/cfg/config_schema.json
Adding usw2-lax-az1 to schema
Closes #441
=> Adding LAX local zone to schema

.travis.yml
=> Enable travis builds

.travis.yml
Sync dev version with target release
=> Fixes https://github.com/aws-quickstart/taskcat/issues/457

.travis.yml
Fixes https://github.com/aws-quickstart/taskcat/issues/460
=> remove tags conditional for pypi builds

.travis.yml
=> Add Release conditions for pypi

README.md
Fixed various typos in README.
README is a face of the project, it should be perfect!
=> README typos fixed

taskcat/_client_factory.py
when creating clients using `Boto3Cache` retry config is not passed to boto, resulting in the default of 4. This ups that to 20, which will also add more backoff and randomness to retries, hopefully catering for the busiest of accounts and qs with the most nested stacks.
=> increase boto throttling retries

.travis.yml
=> Adding packaging module to build step

taskcat/_dataclasses.py, taskcat/cfg/config_schema.json, tests/test_dataclasses.py
=> validation for `s3_object_acl`

docs/README.md
Fix links on https://aws-quickstart.github.io/taskcat
Tested in GH preview
-
https://github.com/aws-quickstart/taskcat/pull/495/commits/7efc9f7a69b72919a32d859e715024dbc89b01d3#diff-e70100059cc3a7376740bbe9751a082e
=> Fix anchors in README

dev-requirements.txt
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
=> Remove duplicate pre-commit req

.travis.yml, setup.py, taskcat/_amiupdater.py, taskcat/_cli_modules/test.py
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
=> Add Python 3.8 support

taskcat/_cfn/stack.py
Under some cases taskcat could crash when failing to find a template for a child stack, this should result in a warning, and not a failure. 
Also added an additional check for local files where the base folder in s3 is above the project root.
=> fix crash when child path cannot be resolved

taskcat/_cli_modules/test.py
During development and with local testing it's common to only want to test a subset of regions, or test configurations. Currently, to do this one must edit the project config file, or create a dev config file and point to it when running the test.
This pr adds `--test-names` and `--regions` flags to the `test run command`. They take one or more test/region names as arguments. When provided, only matching tests/regions will be launched. For example:
```bash
taskcat test run -t 2az -r ca-central-1
taskcat test run -r us-east-1,us-west-2
taskcat test run -t 2az
``` 
=> enable testing subsets of projects

taskcat/_cfn_lint.py
follow the same behavior as when running cfn-lint on the commandline. `.cfnlintrc` files in both homedir and project root are parsed and schema overrides incorporated (useful for adding schemas for custom types)
tested against eks quickstart which contains a .cfnlintrc file and custom schema.
=> honor cfnlint config and schema override

taskcat/_cli_modules/test.py, taskcat/_common_utils.py
This is a convienience function. It helps simplify the process for determining what profile a region should use.
unit tests
=> Wrapper around detemrining the appropriate region for a profile. Closes #539

taskcat/_lambda_build.py
`package` on amazon linux could result in folders being owned by root.
=> docker packaging to run builds as current user

taskcat/_amiupdater.py, taskcat/_cfn/threaded.py, taskcat/_cli_modules/deploy.py, taskcat/_cli_modules/test.py, taskcat/_cli_modules/update_ami.py, taskcat/_lambda_build.py, taskcat/regions_to_partitions.py, tests/data/lambda_build_with_submodules/lambda_functions/source/TestFunc/Dockerfile, tests/data/lambda_build_with_submodules/submodules/SomeSub/lambda_functions/source/TestFunc/Dockerfile, tests/data/lambda_build_with_submodules/submodules/SomeSub/submodules/DeepSub/lambda_functions/source/TestFunc/Dockerfile
Fixes package output when using docker in docker (codebuild/dockerized taskcat) and fixes cases where package zips could be owned by root.
=> Docker packaging improvements

taskcat/_lambda_build.py
Intermittently `container.remove()` would time out. Moving the removal to after archive extraction helped reduce the frequency, also catching the exceptions and logging them instead of failing outright.
=> fix intermittent timeout

e2e/pr_bot/handler.py, taskcat/_s3_stage.py
In a Bring-your-own bucket testing model across multiple partitions, it's possible to have a duplicate bucket name. The current method to remove duplicates assumes single-partition. This PR modifies the internal dictionary to leverage bucket name + bucket partition as a key. 
Unit tests. Run-through across multiple partitions.
```
❯ aws --profile govcloud s3 mb s3://andrew-glenn-linux-bastion-test
make_bucket: andrew-glenn-linux-bastion-test
❯ aws --profile china s3 mb s3://andrew-glenn-linux-bastion-test
make_bucket: andrew-glenn-linux-bastion-test
❯ aws s3 mb s3://andrew-glenn-linux-bastion-test
make_bucket: andrew-glenn-linux-bastion-test
```
Snippet of taskcat config:
```
tests:
amznlinux2hvm:
s3_bucket: andrew-glenn-linux-bastion-test
parameters:
BastionAMIOS: Amazon-Linux2-HVM …
```
=> Making S3 stager aware of multiple partitions when sorting distinct buckets

installer/dockerfiles/alpine-master/Dockerfile
Docker builds are failing. This fixes it.
Closes #583
=> Fixing dockerfile.

taskcat/cfg/amiupdater.cfg.yml
Add **Ubuntu 20.04** to support ami-updater
=> Add Ubuntu 20.04 to support ami-updater

.travis.yml, docs/README.md, taskcat/_amiupdater.py, taskcat/_generate_reports.py
Self evident. Will change the default branch to `main` once this is merged in
=> Changing references from master to main

README.md
Documentation fix for examples used to demonstrate parameter precedence.
**N/A**
**N/A**
=> README.md: Fixed mistake parameter precedence examples

taskcat/_cfn/template.py
ran into a situation where a template failed to parse in a project with many templates. Error gave line and col number, but not filename, leaving us with a needle in a haystack. 
This pr traps yaml parsing errors and outputs a helpful error message before raising the original exception.
=> Output filename when template parsing fails.

setup.py
=> Fixing packaging to include additional module

.pre-commit-config.yaml, dev-requirements.txt, taskcat/_amiupdater.py, taskcat/_cfn/stack_url_helper.py, taskcat/_cfn/template.py, taskcat/_cfn/threaded.py, taskcat/_cfn_lint.py, taskcat/_cli.py, taskcat/_s3_sync.py, taskcat/cfg/config_schema.json, taskcat/regions_to_partitions.py, taskcat/testing/_abstract_test.py, taskcat/testing/_cfn_test.py, taskcat/testing/_hooks.py, taskcat/testing/_lint_test.py, taskcat/testing/_unit_test.py, tests/data/regional_client_and_bucket/templates/debug-yaml.template, tests/data/regional_client_and_bucket/templates/debug.template, tests/data/stackurlhelper/badtemplateurl/templates/test.template_nested.yaml, tests/data/stackurlhelper/badtemplateurl/us-east-1/test.template_nested.yaml, tests/data/stackurlhelper/templates/create_test_from_template.py, tests/test_cfn_threaded.py, tests/testing_module/test_base.py, tests/testing_module/test_cfn.py, tests/testing_module/test_hooks.py, tests/testing_module/test_lint.py, tests/testing_module/test_unit.py
Changes to get pylint/etc to cooperate.
=> Housekeeping

taskcat/iam_policy/policy.py, taskcat/iam_policy/tools.py
=> chore: more pylint/formatting/etc fixes

.pylintrc, taskcat/_config.py, taskcat/_dataclasses.py, taskcat/_template_params.py, taskcat/cfg/config_schema.json, tests/test_template_params.py
resolves  #703
ran pre-commit and tested locally by building taskcat
bucket policy was successfully applied in local testing.
Test coverage via pre-commit
-----------------------------------------------------------------
TOTAL                                          4097   1284    69%
=> Adding multi account deployment support for artifact buckets. resolves #703

taskcat/_cli_modules/upload.py
- Adding --exclude-prefix option to upload command
- quick fix
=> quick fix to prev pr

docs/usage/PSUEDO_PARAMETERS.md
Fixes the spelling of alphanumeric
`portray in_browser`
=> Fix spelling

installer/dockerfiles/alpine-develop/Dockerfile, installer/dockerfiles/alpine-main/Dockerfile
=> updated dockerfile

taskcat/_cli_modules/config.py
=> `taskcat configconvert` --> `taskcat config`

.pre-commit-config.yaml, .pylintrc, taskcat/_cli_modules/__init__.py, taskcat/_cli_modules/package_single.py, taskcat/_cli_modules/test.py, taskcat/_lambda_build.py
- `taskcat configconvert` --> `taskcat config`
- updated dockerfile
- updated dockerfile
- Revert "updated dockerfile"
- fixing issue with dockerfile
- Adding package-single subcommand
=> Adding `taskcat package-single` subcommand

installer/dockerfiles/alpine-develop/Dockerfile, installer/dockerfiles/alpine-main/Dockerfile
=> fixing command issue in DockerFile

installer/dockerfiles/alpine-develop/Dockerfile, installer/dockerfiles/alpine-main/Dockerfile, taskcat/_lambda_build.py
=> changed container version back to a 3.8 version do to an issue.

taskcat/_lambda_build.py, taskcat/cfg/config_schema.json
When `taskcat -d package` (note the debug mode) lambda code using a `Dockerfile` if the execution goes wrong the logs from the container are truncated. This doesn't allow one to easily diagnose problems within the container.
The changes made now collect the logs from a lower level directly from Docker and we get the full container logs not just the last `~n` lines.
Ran `taskcat -d paclage -s functions/source -z functions/output` on the Amazon EKS Architecture quickstart.
Output
```
[INFO   ] : Packaging lambda source from /Users/gargana/workspace/scratch/aws-quickstart/quickstart-amazon-eks/functions/source/ResourceReader using docker image taskcat-build-9f45ebd0ff885208a590b0db185459cd
[DEBUG  ] : docker build logs: 
{"stream":"Step 1/4 : FROM lambci/lambda:build-python3.7"} …
```
=> Patch docker logging

installer/dockerfiles/alpine-main/Dockerfile
=> Updating Docker FIle

taskcat/_dataclasses.py, taskcat/cfg/config_schema.json, taskcat/local_zones.py, taskcat/regions_to_partitions.py
- Adding Israel Region (il-central-1) with update_partition_region_map.py and also ran update_local_zones.py script to update local zones.
- Updated dataclass file with pattern to include `il` for `il-central-1`
- Updated config_schema to include `il` prefix pattern
=> Added Israel (Tel Aviv) - il-central-1, update AZs and updated schemas for new region

taskcat/cfg/amiupdater.cfg.yml
RHEL HA 8.3 (EOL) removed
RHEL HA version (8.6, 8.7, 8.8, 9.0, 9.1, 9.2) added 
RHEL HA 8.4 and 8.5 filter adjusted
> Brief description of what this PR does, and why it is needed (use case)?
Adds further AMI mappings to the upstream amiupdater config for RHEL HA 8 and 9, removes one EOL version.
> How did you validate the changes in this PR?
I used this config to publish the following example Mapping table without issues, I did a validation by picking some AMI id's at random and manually verify that they are available in the region and point to the right AMI.
```
Mappings:
AWSAMIRegionMap:
"us-east-1":
RHELHA84HVM: "ami-0c7598841d2dba4f4"
RHELHA85HVM: "ami-0bd50e308e4cf942a"
RHELHA86HVM: "ami-0d24b5d367ff2557b"
RHELHA87HVM: "ami-036333d7d902c93ec"
RHELHA88HVM: "ami-050aa53cc9e0aa492" …
```
=> feat(amiupdater): RHEL HA removals and additions

requirements.txt
PyYAML to ~= 6.0.1; [1]
urllib3 < 2; [2]
requests to 2.31.0 (latest available)
Ref:
[1]: https://github.com/aws-ia/taskcat/issues/802
[2]: https://github.com/boto/botocore/issues/2926
[3]: Because I feel like it
=> Dependency fixing; Closes #802

pyproject.toml
=> Release: v0.9.50

pyproject.toml
=> Release: v0.9.54

pyproject.toml
=> Release: v0.9.55

CODEOWNERS
Remove jaymccon from codeowners :(
=> chore: Remove jaymccon from codeowners
